# Generated by Django 3.0 on 2020-07-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20200704_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
